[package]
  name = "lightdotso-redis"

  version.workspace = true
  edition.workspace = true
  rust-version.workspace = true
  license.workspace = true
  homepage.workspace = true
  repository.workspace = true

[dependencies]
  futures = { workspace = true }
  lazy_static = { workspace = true }
  lightdotso-tracing = { workspace = true }
  rand = { workspace = true }
  redis = { version = "0.23.2", features = ["tls-native-tls"] }
  tokio = { workspace = true }
