# fly.toml app configuration file generated for lightdotso-loki on 2023-09-08T02:35:43-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lightdotso-loki"
primary_region = "sjc"

[build]
  dockerfile = "./Dockerfile"

[http_service]
  internal_port = 3100
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 3
  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

[[mounts]]
  source = "loki_storage"
  destination = "/loki"
