# fly.toml app configuration file generated for lightdotso-polling-live on 2023-10-03T00:21:50-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lightdotso-polling-live"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  entrypoint = ["/usr/local/bin/polling"]

[build]
  image = "ghcr.io/lightdotso/lightdotso:latest"

[deploy]
  strategy = "canary"

[http_service]
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[metrics]]
  port = 9091
  path = "/metrics"
