[package]
name = "light-wallet-core"
version = "0.1.0"
edition = "2021"

license = "MPL-2.0"

[lib]
name = "uniffi_lightwallet_core"
crate-type = ["staticlib", "cdylib"]

[dependencies]
uniffi = "0.23.0"
uniffi_macros = "0.23.0"

light-wallet-keychain = { path = "../keychain" }

[build-dependencies]
uniffi_build = { version = "0.23.0", features = ["builtin-bindgen"] }
